clearvars vehicle
%Atlas V 411
%   1x Aerojet SRB + 1x RD-180
%   RD-180 (Common Core Booster)
%   RL-10C-1 (Centaur)
%Data taken from:
%   http://spaceflight101.com/spacerockets/atlas-v-411/
%   http://www.spacelaunchreport.com/atlas5.html#components
%   http://www.astronautix.com/a/atlasv.html    (when in doubt)
if ~exist('payload', 'var')
    payload = 12150;    %theoretical to 200km x 28.5°
end
scaleTo = 97;
SpaceShuttleThrustProfile               %use time-scaled STS SRB thrust profile

%SRB + RD-180
stage_m0 = (21054+284089+947+182) + ... %CCB + fuel + interstage + aft stub adapter
            46697 + ...                 %SRB
            (2243+20830) + 2127 + ...   %Centaur + short PLF
            payload;
stage_engines(1) = struct('mode', 1,...
                          'isp0', 338,...
                          'isp1', 311,...
                          'flow', 3827000/(311*g0),...
                          'data', [0.470 1.000]);   %RD-180
stage_engines(2) = struct('mode', 2,...
                          'isp0', 275,...
                          'isp1', 245,...
                          'flow', 1688400/(245*g0),...
                          'data', thrustProfile);   %1 SRB
stage_time = 100;
stage_area = pi*(5.4/2)^2;
stage_drag = [ 0.0  0.08;
               250  0.08;
               343  0.80;
               999  0.50;
               9999 0.40; ];            %not supported by any real data!
stage = struct('MODE', 1,...
               'm0', stage_m0,...
               'engines', stage_engines,...
               'maxT', stage_time,...
               'gLim', 0,...
               'area', stage_area,...
               'drag', stage_drag);
vehicle(1) = stage;

stage_m0 = (21054+284089+947+182) + ... %CCB + fuel + interstage + aft stub adapter
            4000 + ...                  %spent SRB that we're dragging with us until Q gets low enough to safely jettison it
            (2243+20830) + 2127 + ...   %Centaur + short PLF
            payload;
stage_engines(2) = [];
stage.engines(2) = [];
stage_m0 = stage_m0 - vehicleTools('mass', stage, 1, stage_time);
stage_time = 198.4 - vehicle(1).maxT;
stage = struct('MODE', 1,...
               'm0', stage_m0,...
               'engines', stage_engines,...
               'maxT', stage_time,...
               'gLim', 0,...
               'area', stage_area,...
               'drag', stage_drag);
vehicle(2) = stage;

stage_m0 = (21054+284089+947+182) + ... %CCB + fuel + interstage + aft stub adapter
            (2243+20830) + 2127 + ...   %Centaur + short PLF
            payload;
burnt_fuel = vehicleTools('mass', stage, 1, 198.4);
stage_m0 = stage_m0 - burnt_fuel;
stage = struct('MODE', 2,...
               'm0', stage_m0,...
               'engines', stage_engines,...
               'maxT', stage_time,...
               'gLim', 5,...
               'area', stage_area,...
               'drag', stage_drag);
stage.maxT = vehicleTools('tgo', stage, 2, [284089-burnt_fuel 5]);
vehicle(3) = stage;

stage_m0 = 2243+20830 + 2127 + payload; %Centaur + PLF + payload (will be jettisoned via event)
stage_engines(1) = struct('mode', 1,...
                          'isp0', 449.7,...
                          'isp1', 449.7,...
                          'flow', 101800/(449.7*g0),...
                          'data', [1.000 1.000]);   %RL-10C-1
stage_area = pi*(3.05/2)^2;
stage = struct('MODE', 1,...
               'm0', stage_m0,...
               'engines', stage_engines,...
               'maxT', 0,...
               'gLim', 0,...
               'area', stage_area,...
               'drag', stage_drag);
stage.maxT = vehicleTools('tgo', stage, 1, 20830);  %Centaur fuel
vehicle(4) = stage;

clearvars payload
clearvars scaleTo thrustProfile
clearvars stage_m0 stage_time stage_area stage_drag burnt_fuel stage_engines stage