%continueFlight.m
%Converts results from a previous flight into initial conditions for
%another.
%Windspeed is an obsolete feature, in a 3D simulation air-related velocity
%will be recalculated every iteration.
function [initial] = continueFlight(results, windspeed)
    n = length(results.Plots.t);
    initial = struct('type', 1,...
                     't', results.Plots.t(n),...
                     'alt', results.Plots.alt(n),...
                     'rad', results.Plots.rad(n),...
                     'vx', results.Plots.vx(n),...
                     'vy', results.Plots.vy(n),...
                     'wind', windspeed);
end