clearvars vehicle
%Full model of the Space Shuttle, 4 stages:
%   SSME + SRB
%   constant-thrust SSME mode
%   acceleration-limiting SSME mode
%   OMS
%Data taken from:
%   http://www.braeunig.us/space/specs/shuttle.htm
%   http://www.braeunig.us/space/specs/orbiter.htm
%   https://en.wikipedia.org/wiki/Space_Shuttle_orbiter#Shuttle_Orbiter_Specifications_.28OV-105.29
orbiter = 79135;        %OV-105 Endeavour, full OMS/RCS fuel tanks
payload = 25000;        %max for Endeavour

%SRB+SSME
stage_mode = 1;                                     %constant-thrust    | see flightSim3D for details
stage_m0 = 2*587000 + 765000 + orbiter + payload;   %launch mass [kg]   | SRBs + ET + orbiter + payload
stage_thrust = 2*12000000 + 3*1750000;              %thrust ASL [N]
stage_isp1 = 257.7;                                 %ISP ASL [s]
stage_isp0 = 291.2;                                 %ISP VAC [s]
stage_time = 124;                                   %SRB burn time [s]
stage_area = 2*10.8 + 55.4 + 15.2;                  %cross section [m2]
stage_drag = [ 0.0  0.08;
               250  0.08;
               343  1.20;
               999  0.50;
               9999 0.40; ];                        %drag curve - not supported by any real data!
stage_dm = stage_thrust / (stage_isp1*g0);          %total mass flow rate [kg/s]
stage = struct('SM', stage_mode,...
               'aL', 0,...
               'm0', stage_m0,...
               'dm', stage_dm,...
               'i0', stage_isp0,...
               'i1', stage_isp1,...
               'mt', stage_time,...
               'ra', stage_area,...
               'dc', stage_drag);
vehicle(1) = stage;

%SSME const-thrust
stage_m0 = 765000 + orbiter + payload;
stage_thrust = 3*1750000;
stage_isp1 = 366;
stage_isp0 = 452;
stage_time = 320;                                   %acceleration exceeds 3G after that time
stage_dm = stage_thrust / (stage_isp1*g0);
stage_m0 = stage_m0 - 124*stage_dm;                 %SSMEs burned some of the fuel in ET away
stage = struct('SM', stage_mode,...
               'aL', 0,...
               'm0', stage_m0,...
               'dm', stage_dm,...
               'i0', stage_isp0,...
               'i1', stage_isp1,...
               'mt', stage_time,...
               'ra', stage_area,...
               'dc', stage_drag);
vehicle(2) = stage;

%SSME g-limited
stage_mode = 2;                                     %constant-acceleration
stage_m0 = stage_m0 - stage_time*stage_dm;
stage_accLim = 3*g0;
stage_fuel = 80500;                                 %fuel left after previous stages
stage_time = (stage_isp0*g0/stage_accLim) * log(stage_m0 / (stage_m0-stage_fuel));
                                                    %constant-acceleration is a little more complicated
stage = struct('SM', stage_mode,...
               'aL', stage_accLim,...
               'm0', stage_m0,...
               'dm', stage_dm,...
               'i0', stage_isp0,...
               'i1', stage_isp1,...
               'mt', stage_time,...
               'ra', stage_area,...
               'dc', stage_drag);
vehicle(3) = stage;

%OMS
stage_m0 = orbiter + payload;
stage_thrust = 2*26700;
stage_mode = 1;
stage_isp1 = 313;
stage_isp0 = 313;
stage_time = 590;                                   %calculated to satisfy capability of 305 m/s delta-v for a loaded orbiter with 29.5 ton payload
stage_area = 15.2;
stage_dm = stage_thrust / (stage_isp1*g0);
stage = struct('SM', stage_mode,...
               'aL', 0,...
               'm0', stage_m0,...
               'dm', stage_dm,...
               'i0', stage_isp0,...
               'i1', stage_isp1,...
               'mt', stage_time,...
               'ra', stage_area,...
               'dc', stage_drag);
vehicle(4) = stage;

clearvars orbiter payload
clearvars stage_mode stage_m0 stage_thrust stage_isp0 stage_isp1 stage_time stage_area stage_drag stage_dm stage_accLim stage_fuel stage